### ISSUE TITLE
Add async update option.

### ISSUE THREAD

**Issue by hillbrad** [mikewest/origin-policy#10]
It may often be the case that a server with a new policy available is nonetheless sufficiently satisfied with the version of the policy a client has to not mandate a synchronous update and the time-to-interact delays that would incur.  Consider adding a token to instruct the UA to download the new policy asynchronously and continue using its cached policy for the current request.  If no cached policy exists, download could be synchronous always.

**Comment by mikewest** [comment]
Sorry; I haven't done this yet because I don't know how to spell it. Yes. That's a stupid reason not to have done it.

Basically, I'm looking for resolution on the JFV draft in the HTTP WG, which I thought was how we were going to spell headers going forward, but now looks like folks are backing away from it. I haven't yet formed a strong opinion about whether that's a good idea, but I'm leaning towards JSON being the right thing to do for the web side of things, regardless of its inherent imperfections. Will follow up on various threads.

**Comment by domenic** [comment]
How does async update work? I see two options:

1. There is only ever one canonical origin policy per origin. Async updates update them in-place.
2. There can be more than one origin policy per origin, but only one active at a time. Async update puts an inactive one in the store, and then it gets swapped to active upon some event. (Navigation? Agent cluster creation?) This potentially means different windows for the same origin could have different origin policies at a given time.

I guess we probably want (1). Here are some strange, but probably livable, consequences of that:

- The world effectively looks a lot like (2) for certain individual policies, e.g. CSP or feature policy, since those can't (?) be updated after page load. So you could have one window with an older feature policy, and one with a newer one.
- On the other hand, other policies, like the default referrer policy, can suddenly change. So you could do fetches within the first few seconds of loading your page that use one referrer policy, but then the async update happens, and now future fetches use a new referrer policy.

**Comment by annevk** [comment]
I don't think we should introduce more ways to mutate document policies. Looking at the latest origin policy when creating a new document might make sense. It might also make sense that the origin policy lasts for the duration of the agent cluster. (I kinda like that last one, but a problem is the kill switch which would have to reload and effectively force the creation of a new browsing context or some such, ala COOP.)

**Comment by domenic** [comment]
I think copying when creating the document is probably the best we can do, then. So I guess one origin policy per origin in the "origin policy store" (per #47, maybe that's just the HTTP cache), plus one per document---which is not a pointer, it's a full data structure.

**Comment by annevk** [comment]
And one per worker, which are similar to documents.

**Comment by mikewest** [comment]
> I don't think we should introduce more ways to mutate document policies.

I agree with this. I would prefer that we build a clear understanding of a document's policy state when we commit the navigation, and not update it after the fact. Using whatever policy we have at commit-time, fetching the new policy in the background, and using it on the _next_ commit makes sense to me. I'm not sure that tying the policy to the agent cluster instead makes sense, except in cases where the policy change would force the creation of a new agent cluster (e.g. some sort of origin-based isolation opt-in).

**Comment by annevk** [comment]
Coupled to the agent cluster you never have to worry if your frame, popup, or dedicated worker ends up with a different policy. That seems nice and principled. But you're right that it doesn't make as sense if the boundary of the agent cluster is not the origin as the agent cluster would have multiple policies, each added at a different time, which is far from great.

**Comment by domenic** [comment]
This is now incorporated into the explainer in https://github.com/WICG/origin-policy/blob/master/version-negotiation.md, so let's close this issue. I'll work on getting it into the spec soon.

If you have any comments on the proposed async update mechanism there, please let us know!
