### ISSUE TITLE
Defining a new origin-policy member

### ISSUE THREAD

**Issue by mnot** [mikewest/origin-policy#15]
The spec doesn't say how new members are defined; can it be done by publishing a W3C spec, or is there a registry? 

Setting up registries is cheap...

**Comment by domenic** [comment]
Since the move away from header-based configuration, it seems like each origin policy member will require specific processing model handling, here and in the relevant specs. So I don't think a registry or similar will make much sense.

In the end, all members of the origin policy manifest should be specified in this specification, I believe.
