### ISSUE TITLE
JSON structure

### ISSUE THREAD

**Issue by dhausknecht** [mikewest/origin-policy#19]
Since it is clear that we are talking about headers to be included I propose to restructure the JSON to group by "baseline", "fallback","cors-preflight". This eliminates the need for the the "type" attribute.

`“baseline”: {`
`  <baseline headers here>`
`},`
`“fallback”: {`
`  <fallback headers here>`
`},`
`“cors-preflight”: {`
`  <fancy CORS stuff here>`
`}`

**Comment by annevk** [comment]
I'm not sure that's a good model. While they're headers now, I would expect that any additions once this is deployed would not be of that variety. Somewhere in the future "baseline" and "fallback" might end up being rather confusing.

What we could do though is that instead of a top-level "headers", we directly start with "content-security-policy", "referrer-policy", etc. I don't really see why that warrants another level of nesting.

**Comment by annevk** [comment]
(And also, you don't need to define the "type" attribute most of the time anyway since it has a default value. The examples don't make use of this however for some reason.)

**Comment by dhausknecht** [comment]
fair points. And I always support simplicity.

But I wonder which is then the behaviour of Origin Policy. Let's say in our manifest we do have a CSP defined. Do we follow the fallback or the baseline strategy (for CSP this would be a parallel CSP)?

Looking at [HSTS](https://tools.ietf.org/html/rfc6797#page-19) it says that 
> If a UA receives more than one STS header field in an HTTP response message over secure transport, then the UA MUST process only the first such header field

So parallel headers would only make things more complicated. A fallback behaviour is IMO generally applicable and therefore better.

**Comment by annevk** [comment]
I wasn't really suggesting we'd do away with fallback (I was thinking we'd keep the nested value and type keys basically). Maybe even simpler would be "strict-transport-security" and "strict-transport-security-fallback" as keys and their values are strings required to match the ABNF of the header. So use a "-fallback" suffix as an additional key for headers where that makes sense.

**Comment by dhausknecht** [comment]
honestly, I don't see much difference (see the transformed example from the current draft below). Either way we can kick out the "type" attribute which is the real improvement for me. I find mine a bit clearer cause you see the fallback vs baseline better. But I must admit that this is a matter of taste and personal preference.

**dhausknecht version**
`{`
`  "fallback": [`
`    "Content-Security-Policy": "script-src 'self' https://cdn.example.com",`
`    "Referrer-Policy": "origin-when-cross-origin"`
`  ],`
`  "baseline": [`
`    "Content-Security-Policy": "object-src 'none'; frame-ancestors 'none'",`
`    "Strict-Transport-Security": "max-age=10886400; includeSubDomains; preload",`
`    "X-Content-Type-Options": "nosniff"`
`  ],`
`  "cors-preflight": {`
`    "origins": "*"`
`  }`
`}`

**annevk version**
`{`
`  "Content-Security-Policy-fallback": "script-src 'self' https://cdn.example.com",`
`  "Referrer-Policy-fallback": "origin-when-cross-origin",`
`  "Content-Security-Policy": "object-src 'none'; frame-ancestors 'none'",`
`  "Strict-Transport-Security": "max-age=10886400; includeSubDomains; preload",`
`  "X-Content-Type-Options": "nosniff",`
`  "cors-preflight": {`
`    "origins": "*"`
`  }`
`}`

**Comment by annevk** [comment]
I think mine is better as it doesn't treat headers in a special way. It just so happens that some keys have the same value as similar-named headers.

Per https://w3ctag.github.io/design-principles/#casing-rules JSON keys need to be lowercase and underscore-delimited by the way, though I'm not sure the latter really makes sense given we're effectively mapping them to HTTP headers. @domenic?

**Comment by domenic** [comment]
I mean, it depends on whether these are supposed to be headers, or just have the same affect as headers. It sounds like the latter, especially if you're saying that in the future it will include non-headers. In which case I'd suggest sticking with the platform casing rules for JSON instead of for headers.

**Comment by annevk** [comment]
Note that there's plenty of precedent for hyphens too, e.g., https://w3c.github.io/webappsec-csp/ and https://wicg.github.io/reporting/. That seems somewhat preferable to underscores as a general pattern.

**Comment by dhausknecht** [comment]
> I think mine is better as it doesn't treat headers in a special way.

This implies that we need to define a list of all supported key values, doesn't it? But you are right, it removes the header or non-header distinction in the manifest file which is pretty nice.

thanks for the comments on JSON formatting. I am not sure if "Client-side API Design Principles" is the right reference here since Origin Policy will not have a JavaScript API, will it? In that case we can more or less do what we want. We have to define a list of allowed key-value pairs anyway. This will define precisely what we expect, everything else we just ignore (and probably show a warning at some point).

**Comment by annevk** [comment]
> This implies that we need to define a list of all supported key values, doesn't it?

Yeah, I think we need to do that anyway. We don't necessarily want to support all headers here (e.g., Content-Type or Content-Length) so we'll need to define which are supported anyway. Coupled with naming restrictions (and guidelines) and JSON being case-sensitive and headers not, I don't see a way out of this one.

> I am not sure if "Client-side API Design Principles" is the right reference here since Origin Policy will not have a JavaScript API, will it?

It's about APIs in a broad sense of the word, HTML elements and JSON resources are part of it.

**Comment by mikewest** [comment]
After talking things through with @mnot a while ago, I'm pretty sure that a header-based model is the wrong one for the manifest format we're putting together. So, I agree with both of your suggestion that we enumerate the things that the manifest can control, and drop the `headers` property in favor of explicit properties for the various things that come up. I thought I'd done that already, honestly, but apparently I only wrote the patch in my head. :/

I'd also suggest that we don't need to have a 1:1 mapping between header syntax and manifest syntax. For example, the `Strict-Transport-Security` header has a `max-age` property because its expiration needs to be distinct from the expiration of the resource with which it's delivered. I think we can do away with that in the manifest, and instead tie the lifetime of the pinned HSTS policy to that of the manifest. That is, you could imagine a set of HTTP configuration options along the lines of:

```
{
  ...,
  "tls": {
    // Strict-Transport-Security
    "required": true,

    // Public-Key-Pins / Public-Key-Pins-Report-Only
    "pinned-public-keys": {
      "pins": [
        "d6qzRu9zOECb90Uez27xWltNsj0e1Md7GkYYkVoZWmM=",
        "E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=",
        "LPJNul+wow4m6DsqxbninhsWHlwfp0JecwQzYpOLmCQ="
      ],
      "disposition": "enforce",
      "report-to": "group-name",
    },

    // Expect-CT
    "certificate-transparency": {
      "disposition": "enforce",    // (or "report-only")
      "report-to": "group-name"
    },

    // Others. `Expect-Staple`, etc.
    ...
  },
  ...
}
```

Referrer policy and CSP might look like:

```
{
  ...,
  "referrer": {
    "policy": "origin-when-cross-origin",
    "allow-override": true
  },
  "content-security-policy": [
    {
      "policy": "frame-ancestors 'none'; object-src 'none';",
      "disposition": "enforce",
    },
    {
      "policy": "script-src 'self' https://cdn.example.com/js/",
      "disposition": "enforce",
      "allow-override": true
    },
  ],
  ...
}
```

Client hints could be:

```
{
  ...,
  "client-hints": [ "DPR", "Width", "Viewport-Width" ],
  ...
}
```

CORS could be:

```
{
  ...,
  "core-preflights": {
    "no-credentials": {
      "origins": "*",
    },
    "unsafe-include-credentials": {
      "origins": [ "https://trusted.example.com/" ]
    },
  },
  ...
}
```

Etc.

**Comment by mnot** [comment]
Awesome. Am glad to help however you'd like. Really want to see this one moving with bells on, so we can stop minting crap headers.

**Comment by lgarron** [comment]
I have considered trying to update the preload list format to handle different security mechanisms more consistently, and your format looks like a good generalization of that. It would be nice if we could reuse it in Chromium (assuming we're comfortable with the backwards incompatibility risk) or other serializations of security mechanism configuration data.

> I think we can do away with that in the manifest, and instead tie the lifetime of the pinned HSTS policy to that of the manifest.

This makes me worried:
- I don't think the two values should be correlated.
  - Chrome [currently](https://crbug.com/692348) caps dynamic HSTS at one year, and Firefox has it unlimited. We [recommend 2 years for HSTS `max-age`](https://hstspreload.org/#deployment-recommendations) at hstspreload.org
  - Chrome caps HPKP at 60 days.
  - It seem desirable to me for HSTS to outlast the origin policy itself. I would still want to prevent MitM when the user comes back after a few months, even if I don't want all my origin policy details to last that long.
- Since the manifest is already meant to be served rarely (and cached), I don't think the extra space would be a big issue.
- The HSTS header right now is simple to find, parse, and interpret from all clients/user agents. This sounds like it would require scanning tools to look in even *more* places (original request headers, manifest content, manifest lifetime), for data, parse that data, and hope they combine it correctly. I think putting it in the manifest itself will cause minimal statistics bugs and security incidents.
- It seems that origin policies (or headers indicating where it is which version to use) are meant to be served dynamically based on client state and maybe user agent. From my hstspreload.org scans, it already seems hard enough to get sites to set a single static header value and keep serving it. Serving a static origin-ish origin policy with explicit encoded max-ages sounds like a reasonable intermediate.

Also, we need a way to specify `includeSubDomains` and `preload` for HSTS. Those should probably be grouped instead of being placed into `tls` directly.

**Comment by annevk** [comment]
@lgarron #25 also has some HSTS concerns; would be good to get your feedback there.

**Comment by domenic** [comment]
The structure has changed significantly, as a result of this discussion, with the current proposal in https://github.com/WICG/origin-policy/blob/master/version-negotiation.md. Let's close this issue, and open new ones for issues with the new proposal.
