### ISSUE TITLE
Benefit of Sec-Origin-Policy request header

### ISSUE THREAD

**Issue by jakearchibald** [mikewest/origin-policy#23]
It isn't clear what the benefit of the `Sec-Origin-Policy` request header is.

I get that it advertises support for the feature, but why should it broadcast the version it has?

**Comment by annevk** [comment]
That way the server doesn't have to transmit the manifest if it hasn't changed.

**Comment by jakearchibald** [comment]
As in, avoid http/2 pushing it? Or avoid sending the `Sec-Origin-Policy` response header?

Cache digests should cater for the push thing.

**Comment by annevk** [comment]
Are cache digests an actual thing these days? Do we want to depend on them? Might be reasonable, dunno. I think that's effectively what it does, but @mikewest can say more.

**Comment by jakearchibald** [comment]
Cache digests aren't implemented yet, but they're the general fix for "don't push what I already have", so adding a header to solve the same problem specifically for origin-policy seems bad.

**Comment by annevk** [comment]
cc @mnot

**Comment by mikewest** [comment]
I'd like to get rid of the identifier advertised in the request, as it really complicates things like third-party cookie blocking (because we'd want to treat the identifier in the same way we treat cookies, as it's server-controlled), so I hope we can find a way to do so.

We send the `Sec-Origin-Policy` header so that the server can decide what headers it sends back. Knowing that a manifest is active for a given user means that the server can, for example, avoid sending 4k of CSP on every response, which seems like a win.

We originally reflected the active policy version in the header for the reason @annevk suggests: knowing the active manifest for a given user agent means that the server can initiate a push for the manifest only in cases where it knows that an update is necessary (See Facebook's comments at https://lists.w3.org/Archives/Public/public-webappsec/2016Jul/0058.html). Cache digests might be enough for this use case, though I'm pretty sure they're probabilistic in nature, so wouldn't be a perfect solution (and they have privacy implications similar to cookies, so I imagine some subset of users would be blocking them in third-party contexts).

If we're happy relying on cache digests for the push problem, then we can probably remove the entropy from the request header by making the response header more complicated to handle client-side rulesets that would support the `async`/`sync` distinction that was discussed in https://lists.w3.org/Archives/Public/public-webappsec/2016Jul/0073.html.

**Comment by mnot** [comment]
Yeah, we discussed this before. HTTP already has `ETag` validation to avoid transfers and assure that the client has the right version.

I'm not sure what the use case for the current design is. IIRC there was something about supporting multiple versions of a policy concurrently, but even then, HTTP should be able to do the right thing (by setting appropriate Vary, etc.).

This approach seems overly complex / special-cased. Can't it just be a flag?

**Comment by annevk** [comment]
So thinking about this more I think we don't want to rely on the HTTP cache completely, because we need this thing to persist much longer. Otherwise moving HSTS to an origin policy is rather pointless for instance. So you can't really store these resources in the HTTP cache as that makes the whole setup much less reliable.

**Comment by mnot** [comment]
Sure, but that doesn't mean you can't use HTTP validation.

**Comment by dhausknecht** [comment]
I think the misunderstanding is that currently policies are directly tied to their names. When you receive the header `Sec-Origin-Policy: "policy-1"` you fetch it from `.well-known/origin-policy/policy-1`, when you receive `Sec-Origin-Policy: "policy-XYZ"` you fetch it from `.well-known/origin-policy/policy-XYZ` and so on. That means the URL changes with every new policy. We might want to change that and then suddenly `ETag` makes much more sense. We only want to have a single policy at a time anyway, don't we?

There are however two problems I see with it:

1. we cannot say "you should have a policy version of at least X or newer". We should probably discuss (non-)sense of this feature in a new thread.
2. user tracking. We thought about deleting manifests whenever cookies are deleted since the policy identifier can otherwise be used as a user identifier, similar to how ETags where abused already in the past. The draft has a section on the [user tracking](https://wicg.github.io/origin-policy/#tracking) issue.

**Comment by annevk** [comment]
The tracking is a valid concern, but I'm not sure it deserves to overrule HSTS. Perhaps we need to special case HSTS somehow or maybe exclude it from origin policies on that basis?

**Comment by dhausknecht** [comment]
uh, wasn't HSTS one of *the* motivations for the whole thing? In any case, excluding this (and potentially others) right from the beginning would kind of question the whole endeavour of having a single point of origin configuration and just feel wrong IMHO.
If this implies we cannot use ETag, so be it. I just tried to not disregard the idea of ETag immediately. It gets close to what we need after all.

**Comment by annevk** [comment]
Personally I think HSTS is a pretty poor motivation since it's already cached origin-wide and can be preloaded.

CSP, CORS, isolation policies, etc. are much better motivations and wouldn't be hurt by not being persistent.

**Comment by mikewest** [comment]
@annevk: I agree completely that we wouldn't want to rely on the resource actually being in the HTTP cache. I was instead suggesting that we can use the semantics of HTTP caching to understand how long we ought to retain the parsed manifest and apply it to a given profile (e.g. instead of adding in an expiration/max-age to the header).

With regard to HSTS, part of my goal with this feature is to provide a mechanism for defining these kinds of origin-wide configurations in a non-resource-specific way. I agree with you that it's currently cached origin-wide and preloaded, but in a world where this feature already existed, I hope we wouldn't have defined HSTS as a header on any response from the origin. Those kinds of assertions should be delegated to a single, trustworthy configuration point, rather than allowing any resource to make assertions on the origin's behalf.

As you note, CSP, CORS, etc. are good examples of other kinds of things that can fit into the same mold, and would be valuable to define at a single point.

That said, we're getting a bit far afield from the specific topic at hand. The use case that @hillbrad spelled out in the threads linked above (in particular https://lists.w3.org/Archives/Public/public-webappsec/2016Jul/0058.html) seems reasonable to me. `Sec-Origin-Policy` allows us to meet those needs, but with some risk to user privacy insofar as it creates another cookie-like tracking mechanism that sends a server-generated string along with requests to the origin. If we can come up with another way of meeting those needs, great! It's not clear to me that `etag` does so, but I'd be happy to learn I'm wrong. :)

**Comment by mnot** [comment]
If ETags are a tracking problem worth solving, we should fix it across the board, for all HTTP resources. Doing it piecemeal by reinventing new mechanisms for each possible use just makes the space messier, and doesn't solve the bigger problem; ETags will still be used, potentially on all other resources on the origin.

Besides which, `Sec-Origin-Policy` is a *new* tracking vector, whereas at least people (and implementations) that care about it are already somewhat aware of the problems with ETags.

Another big benefit of that approach is that you don't need special handling on the server side; you can just deploy the file.

@mikewest going to Brad's mail:

> 1) If I'm reading this correctly, you could never have a more relaxed CSP for a specific resource than the baseline value in an Origin Policy due to the way header combination works for CSP.  It seems like some sort of escape hatch is necessary to disable Origin-Policy processing for a given response?  (or you have to be absolutely 100% certain about the baseline policy contents and probably still send large delta policies with almost every request)

I think this depends very much on what we want to use OP for. If we do want resource-specific behaviour, that to me is a strong argument for favouring the header-based model, and allowing specific response headers to override the data in OP (as per my proposal way back when). But it's not at all clear to me that this is appropriate for the use cases we're talking about these days; personally, I'd rather Let Origin Policy be Origin Policy for reals.

> 2) Another smart person at FB points out that the benefit of having the client send which version it is currently enforcing for the domain is that you can avoid having to do an H2 push for every request to avoid blocking. Seems like a big deal, so maybe the "cookie-like" semantics are a big win, after all.

Odd. My assumption was that in the common case, the server would push an OP at the beginning of a connection, or upon learning of a new one. That wouldn't require knowing what the client currently holds for every request, at least for the purposes of push.

That said, having something to `Vary` on concretely would be nice if we want to conditionally emit headers on responses based upon what origin policy the client holds, per request. If that's a use case, we again might want to reconsider what the relationship between OP and headers is.

> 3) Same smart person is concerned about being able to do graceful upgrade without thrashing if servers don't all see the same policy version as current simultaneously.  I think this might be best accomplished, again, by the original proposal, so the origin owner could encode a versioning scheme into the policy name and a server that is serving policy v1 doesn't try to override a client that says it's already enforcing v2.  (could possibly do this by caching all previous hashes, but that's kind of ugly in the long run)

This is the case when a client gets v2 content from a server, then gets re-balanced to a server that has v1 content. That means that the client will now be applying v2 policy to v1 content -- is that always going to be desirable? 

We should probably dig into this use case more. My gut tells me that this is something that your content distribution / load balancing solution needs to solve, not the protocol.

**Comment by annevk** [comment]
@otherdaniel as I believe you're working on an experimental implementation now, could you perhaps detail what your strategy for mitigating this problem is? I understand if you all want to wait with updating the specification a bit until you're more clear on whether things work out at all, but it would still be good to know to what extent Mozilla and Google align on privacy goals here. (And I should note here that my prior comments did not really take those into consideration.)

**Comment by otherdaniel** [comment]
In a personal first, literally every bit of feedback received on the Origin Policy version negotiation has been negative. We're pretty sure the version mechanism - as currently spec'ed - won't stand, but we're not quite sure what should replace it.

For the time being, our current implementation simply drops this, and always sends the 'default' value (as if it was the first site visit).

I had very recently discussed this with Mike, and while we still don't really have a plan I did write down what we're currently doing and - arguably more important - what the use cases are, [here](https://docs.google.com/document/d/1hYCPowNFjESqJWZ3xItDwjMHmvMwuN_0lB3zedDkZaY/edit). Since this is arguably the perfect audience for this, I'd like everyone following along here to read the two "Considered Alternatives", and the problem scenarios at the bottom, and to comment liberally.

----

If it matters, my privacy plan for the original design - no longer relevant - would have been to treat this "cookie" exactly like all other cookies: Make sure it's listed in the site info; deleted on 'clear site data'; and stored separately for regular/incognito mode (and likewise obey any future, stricter separation we might do for the cookie store).
