### ISSUE TITLE
Interaction with suborigins

### ISSUE THREAD

**Issue by annevk** [mikewest/origin-policy#31]
If an origin actually exists of many applications (suborigins), we probably need to offer some additional granularity around CORS and maybe CSP...

**Comment by dhausknecht** [comment]
this should be easily solvable through additional attributes for the respective features. I hope this does not become to messy in the end though :-/

In any case I oppose separate manifest files since that would contradict with the idea of having one single manifest for an entire origin and I expect freaky complications with it.

**Comment by domenic** [comment]
Since suborigins seems stalled, let's close this, effectively punting the answer to the suborigins folks to ensure that if they ever pick up the work, it integrates well with origin policy.
