### ISSUE TITLE
"Suffix" in 2.3.1. is not defined

### ISSUE THREAD

**Issue by MattMenke2** [mikewest/origin-policy#42]
The sentence "Origin Policy Manifest files for a given origin MUST be located as suffixes to the well-known location /.well-known/origin-policy [RFC5785]." doesn't seem to define suffix.

The linked RFC only says: URI suffix:  The name requested for the well-known URI, relative to "/.well-known/"; e.g., "example" (This also seems a bad definition to me, as "../foo" is a URI relative to "/.well-known/").  That's not a general definition of a suffix, just of the suffix member of a URL template, which is a URI "relative" to /.well-known/.

In particular, it's unclear which of the following, if any, are valid suffixes:
* /.well-known/origin-policy-suffix
* /.well-known/origin-policy/suffix
* /.well-known/origin-policy/suffix?more suffix
* /.well-known/origin-policy?suffix
* /.well-known/origin-policy/
* /.well-known/origin-policy%2Fsuffix (This is an escaped "/")
* /.well-known/suffix  // This *is* a URI suffix as defined in the linked RFC.

Edit:  Some other ones:
* /.well-known/origin-policy/%00 (I guess we don't consider this one a valid URL, actually)
* /.well-known/origin-policy/%01
* /.well-known/origin-policy/%81 (invalid UTF-8 character)
* /.well-known/origin-policy/%F0%9F%94%92 (valid UTF-8 character)

**Comment by domenic** [comment]
The [new plan](https://github.com/WICG/origin-policy/blob/master/version-negotiation.md) is to just check `/.well-known/origin-policy`, without any path concatenation. So thankfully this issue is no longer present.

I'll close this, although one should note that the spec is not yet updated to match the explainer. (But it does have a big warning saying to pay attention to the explainer instead.)
